name: talabahamkor_mobile
description: A new Flutter project.
publish_to: 'none'
version: 1.0.4+6

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Networking
  http: ^1.1.0
  http_parser: ^4.0.2
  
  # Storage (JWT)
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.0

  # State Management
  provider: ^6.0.5

  # UI/UX
  google_fonts: ^6.1.0
  intl: 0.20.2
  file_picker: ^8.1.7
  
  # Deep Linking & URLs
  url_launcher: ^6.3.1
  app_links: ^6.3.2
  
  # Icons
  cupertino_icons: ^1.0.8
  cached_network_image: ^3.4.1
  flutter_localizations:
    sdk: flutter
  image_picker: ^1.1.2
  share_plus: ^10.1.4
  flutter_image_compress: ^2.4.0
  path_provider: ^2.1.5

  # Firebase Push Notifications
  firebase_core: ^3.10.1
  firebase_messaging: ^15.2.10

  # Local Database (Offline Persistence)
  sqflite: ^2.3.0
  path: ^1.9.0
  permission_handler: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/logo_final.png
  android_12:
    image: assets/images/logo_final.png
    icon_background_color: "#FFFFFF"
  ios: true
  android: true


flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/logo_final.png"
  min_sdk_android: 21 # optional

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
