name: talabahamkor_mobile
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Networking
  http: ^1.1.0
  
  # Storage (JWT)
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.0

  # State Management
  provider: ^6.0.5

  # UI/UX
  google_fonts: ^6.1.0
  intl: 0.20.2
  file_picker: ^8.0.0
  
  # Deep Linking & URLs
  url_launcher: ^6.1.11
  app_links: ^6.3.0
  
  # Icons
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.4.1
  flutter_localizations:
    sdk: flutter
  image_picker: ^1.2.1
  share_plus: ^12.0.1
  flutter_image_compress: ^2.4.0
  path_provider: ^2.1.5

  # Firebase Push Notifications
  firebase_core: ^3.10.1
  firebase_messaging: ^15.2.1

  # Local Database (Offline Persistence)
  sqflite: ^2.3.0
  sqflite: ^2.3.0
  path: ^1.9.0
  permission_handler: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/logo_final.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
